spring:
  application:
    name: back

  datasource:
    url: jdbc:mysql://localhost:3306/taxishare
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect

  kafka:
    bootstrap-servers: localhost:9092

  docker:
    compose:
      enabled: false

  doc:
    api-docs:
      path: /v3/api-docs
    swagger-ui:
      path: /swagger-ui.html

  data:
    redis:
      host: localhost
      port: 6379
  cache:
    type: redis
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    prometheus:
      enabled: true
