import type { Metadata } from "next";
import dynamic from 'next/dynamic';
import "./globals.css";
import QueryProvider from './QueryProvider';
// const QueryProvider = dynamic(() => import('./QueryProvider'), {
//   ssr: false,
// });


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <QueryProvider>
          {children}
        </QueryProvider>
      </body>
    </html>
  );
}
